# Create a file called "render.yaml" in your project root:
services:
  - type: web
    name: kroger-analyzer-docker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter  # Use paid plan for Docker support
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /app
      - key: DISPLAY
        value: :99